---
title: "Hierarchical Tennis Model 2 v1"
format:
  html:
    toc: true
    code-tools: true
    code-line-numbers: true
    number-sections: true
    mainfont: Georgia, serif
editor: source
---

# Setup

## Install packages

```{r}
if (!require(tidybayes)) {
    install.packages("tidybayes")
    library(tidybayes)
}

if (!require(tidyr)) {
    install.packages("tidyr")
    library(tidyr)
}

if (!require(brms)) {
    install.packages("brms")
    library(brms)
}

if(!require(ggplot2)) {
  install.packages("ggplot2")
  library(ggplot2)
}

if(!require(reliabilitydiag)) {
  install.packages("reliabilitydiag")
  library(reliabilitydiag)
}


if (!require(metadat)) {
  install.packages("metadat")
  library(metadat)
}

if(!require(cmdstanr)){
    install.packages("cmdstanr", repos = c("https://mc-stan.org/r-packages/", getOption("repos")))
    library(cmdstanr)
}
cmdstan_installed <- function(){
  res <- try(out <- cmdstanr::cmdstan_path(), silent = TRUE)
  !inherits(res, "try-error")
}
if(!cmdstan_installed()){
    install_cmdstan()
}
```

## Configure ggplot

```{r}
theme_set(theme_bw())
```


# Fit model

```{r}
players <- read.csv("../clean-data/players.csv")
```


```{r}
data <- read.csv("../clean-data/master-sub.csv")

head(data)
```

```{r}
df <- data[c("ServerWon", "BreakPoint", "Tiebreaker", "PointServer", "player1id", "player2id", "ServerId")]

str(df$ServerWon)
str(df$BreakPoint)
str(df$Tiebreaker)
str(df$ServerId)
```

```{r}
fit_hier <- brm(
  formula = ServerWon ~ BreakPoint + Tiebreaker +
            (1 + BreakPoint + Tiebreaker | ServerId),
  data    = df,
  family  = bernoulli(link = "logit"),
  prior   = c(
    # standard intercept and slope
    prior(normal(0, 2^2), class = "Intercept"),
    prior(normal(0, 1^2),   class = "b"),
    # hierarchical variation
    prior(student_t(3, 0, 2.5), class = "sd", group = "ServerId")
    # prior(lkj(2),         class = "cor", group = "ServerId")
  ),
  chains  = 4,
  cores   = 4,
  iter    = 2000
)
```

```{r}
summary(fit_hier)
```

# Analyse model

## Plot PPD

```{r}

make_preds <- function(this_fit, n_players = -1) {
  all_ids <- intersect(players$id, df$ServerId)
  op <- players[players$id %in% all_ids,]
  op <- op[order(op$no_matches, decreasing = TRUE),]
  
  idx <- if(n_players < 0) {
    nrow(op)
  } else {
    1:n_players
  }
  player_ids <- op$id[idx]
  
  ppd_reg <- posterior_epred(
    this_fit,
    newdata = data.frame(
      Tiebreaker = 0,
      BreakPoint = 0,
      ServerId = player_ids
    )
  )
  
  ppd_break <- posterior_epred(
    this_fit,
    newdata = data.frame(
      Tiebreaker = 0,
      BreakPoint = 1,
      ServerId = player_ids
    )
  )
  
  ppd_tie <- posterior_epred(
    this_fit,
    newdata = data.frame(
      Tiebreaker = 1,
      BreakPoint = 0,
      ServerId = player_ids
    )
  )
  
  df_reg <- as.data.frame(ppd_reg)
  colnames(df_reg) <- player_ids
  df_reg <- df_reg |>
    pivot_longer(
      cols = everything(),
      names_to = "ServerId",
      values_to = "ppd"
    )
  
  df_break <- as.data.frame(ppd_break)
  colnames(df_break) <- player_ids
  df_break <- df_break |>
    pivot_longer(
      cols = everything(),
      names_to = "ServerId",
      values_to = "ppd"
    )
  
  df_tie <- as.data.frame(ppd_tie)
  colnames(df_tie) <- player_ids
  df_tie <- df_tie |>
    pivot_longer(
      cols = everything(),
      names_to = "ServerId",
      values_to = "ppd"
    )
  
  ids_by_perf <- group_by(df_reg, ServerId) %>%
    summarise(wp = mean(ppd), .groups = "keep") %>%
    arrange(desc(wp)) %>%
    left_join(mutate(players, id = as.character(id)), 
              by = join_by(ServerId == id))
  
  df_reg$ServerId <- factor(df_reg$ServerId,
                            levels = ids_by_perf$ServerId,
                            labels = ids_by_perf$player)
  preds <- data.frame(
    p_reg = df_reg$ppd,
    p_break = df_break$ppd,
    p_tie = df_tie$ppd,
    ServerId = df_reg$ServerId
  )
}
```

### Density plot

```{r}
preds <- make_preds(fit_hier, 4)
p <- ggplot(preds) + 
  geom_density(
    aes(p_reg, colour = 'Any point')
  ) + geom_density(
    aes(p_break, colour = 'Breakpoint')
  ) + geom_density(
    aes(p_tie, colour = 'Tiebreak')
  ) +
  facet_wrap(~ ServerId) +
  xlab('Win probability') +
  ylab('Density')
p
```

### Point estimates plot

```{r}
lpreds <- make_preds(fit_hier, 10) %>%
  pivot_longer(
    cols = starts_with("p_"),
    names_to = "situation",
    values_to = "p"
  )

lpreds$situation <- factor(lpreds$situation,
                           levels = c("p_break", "p_reg", "p_tie"),
                           labels = c("Breakpoint", "Regular point", "Tiebreaker")
                           )

colors <- scales::hue_pal()(3)
colors[1:2] <- colors[2:1]

plt <- ggplot(lpreds, aes(x = p, 
                   y = ServerId, 
                   color = situation
                   )) +
  stat_pointinterval(
    .width = c(0.5, 0.95),
    position = position_dodge(width = 0.6),
  ) +
  scale_color_manual(values = c(cc[2], cc[1], cc[3])) +
  labs(
    title = "Win probability of server at different points",
    color = "Point type",
  ) +
  xlab("Point win probability") +
  ylab("Server")
plt
```

## Additional convergence diagnostics

Sampler diagnostics

```{r}
np <- nuts_params(fit)
head(np)
```

Divergences

```{r}
divergences <- subset(np, Parameter == "divergent__" & Value == 1)
n_div <- nrow(divergences)
n_div
```

Max treedepth hits:

```{r}
treedepth_hits <- subset(np, Parameter == "treedepth__" & Value == max(Value))
nrow(treedepth_hits)
```

## Reliabilitydiag

```{r}
library(brms)
library(reliabilitydiag)

this_fit <- fit_reg

# posterior mean coefficients
b <- fixef(this_fit)  # rows: "Intercept", "BreakPoint", "Tiebreaker"

b0   <- b["Intercept",  "Estimate"]
b_bp <- b["BreakPoint", "Estimate"]

# population level parameter estimates
ests <- ranef(this_fit, probs=c(0.05,0.95))
str_ids <- paste(df$ServerId)
grp0 <- ests$ServerId[str_ids, "Estimate", "Intercept"]
grp_bp <- ests$ServerId[str_ids, "Estimate", "BreakPoint"]

# predicted win prob for each point (plug-in logistic regression)
linpred   <- b0 + b_bp * df$BreakPoint + grp0 + grp_bp * df$BreakPoint
fit_probs <- plogis(linpred)   # length = nrow(df)

# reliability diagram for all points
rd_all <- reliabilitydiag(fit_probs, y = df$ServerWon)
plt <- autoplot(rd_all, type = "miscalibration") +
  coord_cartesian(
    xlim = range(fit_probs),
    ylim = c(0,0.8)
    )
```

## ROC Plot

```{r}
## ROC Plot

# install/load pROC if needed
if (!require(pROC)) {
  install.packages("pROC")
  library(pROC)
}

# posterior mean coefficients
b <- fixef(fit_hier)  # rows: "Intercept", "BreakPoint", "Tiebreaker"

b0   <- b["Intercept",  "Estimate"]
b_bp <- b["BreakPoint", "Estimate"]

# population level parameter estimates
ests <- ranef(fit_hier, probs=c(0.05,0.95))
str_ids <- paste(df$ServerId)
grp0 <- ests$ServerId[str_ids, "Estimate", "Intercept"]
grp_bp <- ests$ServerId[str_ids, "Estimate", "BreakPoint"]

# predicted win prob for each point (plug-in logistic regression)
linpred   <- b0 + b_bp * df$BreakPoint + grp0 + grp_bp * df$BreakPoint
fit_probs <- plogis(linpred)   # length = nrow(df)

# ROC object
roc_obj <- roc(response = df$ServerWon,
               predictor = fit_probs,
               quiet = TRUE)

# base ROC plot with AUC
plot(roc_obj,
     main = "ROC curve for non-hierarchical model",
     xlab = "False positive rate (1 - specificity)",
     ylab = "True positive rate (sensitivity)")
text(0.6, 0.1,
     labels = paste0("AUC = ", round(auc(roc_obj), 3)))

```

## PSIS–LOO

```{r}
loo_fit <- loo(fit_hier, ndraws = 1000)
loo_fit
```

## LOO-PIT-ECDF

```{r}
pp_check(
fit_hier,
type = "loo_pit_ecdf", # LOO-PIT ECDF calibration check
ndraws = 500 # you can adjust if you like
)
```

# Sensitivity analysis

```{r}
priors_reg <- c(
    prior(normal(0, 2),   class = "Intercept"),
    prior(normal(0, 0.5), class = "b"),
    prior(exponential(1), class = "sd", group = "ServerId"),
    prior(lkj(2), class = "cor", group = "ServerId")
)
fit_reg <- update(fit_hier, prior = priors_reg, refresh = 0)

priors_weak <- c(
  prior(normal(0, 10),  class = "Intercept"),
  prior(normal(0, 5),   class = "b"),
  prior(student_t(3, 0, 5), class = "sd", group = "ServerId")
)
fit_weak <- update(fit_hier, prior = priors_weak, refresh = 0)

priors_robust <- c(
  prior(student_t(3, 0, 2.5), class = "Intercept"),
  prior(student_t(3, 0, 2.5), class = "b"),
  prior(student_t(3, 0, 2.5), class = "sd", group = "ServerId"),
  prior(lkj(2), class = "cor", group = "ServerId")
)

fit_robust <- update(fit_hier, prior = priors_robust, refresh = 0)

```

```{r}
fits <- list(
  original = fit_hier,
  narrow = fit_reg,
  wide = fit_weak,
  robust = fit_robust
)

all_preds <- imap_dfr(fits, ~ mutate(make_preds(.x, 1), model = .y))
```

```{r}

plt_reg <- ggplot(all_preds, aes(x = p_reg, colour = model)) + 
  geom_density() +
  facet_wrap(~ ServerId) +
  xlab('Win probability') +
  ylab('Density') +
  labs(title = 'Any point')
plt_reg

plt_break <- ggplot(all_preds, aes(x = p_break, colour = model)) + 
  geom_density() +
  facet_wrap(~ ServerId) +
  xlab('Win probability') +
  ylab('Density') +
  labs(title = 'Break point')
plt_break

plt_tie <- ggplot(all_preds, aes(x = p_tie, colour = model)) + 
  geom_density() +
  facet_wrap(~ ServerId) +
  xlab('Win probability') +
  ylab('Density') +
  labs(title = 'Tiebreak')

plt_tie


```

