---
title: "Non Hierarchical Tennis Model 1 v1"
format:
  html:
    toc: true
    code-tools: true
    code-line-numbers: true
    number-sections: true
    mainfont: Georgia, serif
editor: source
---

## 

```{r}
if (!require(tidybayes)) {
    install.packages("tidybayes")
    library(tidybayes)
}

if (!require(tidyr)) {
    install.packages("tidyr")
    library(tidyr)
}

if (!require(brms)) {
    install.packages("brms")
    library(brms)
}

if(!require(ggplot2)) {
  install.packages("ggplot2")
  library(ggplot2)
}

if(!require(reliabilitydiag)) {
  install.packages("reliabilitydiag")
  library(reliabilitydiag)
}


if (!require(metadat)) {
  install.packages("metadat")
  library(metadat)
}

if(!require(cmdstanr)){
    install.packages("cmdstanr", repos = c("https://mc-stan.org/r-packages/", getOption("repos")))
    library(cmdstanr)
}
cmdstan_installed <- function(){
  res <- try(out <- cmdstanr::cmdstan_path(), silent = TRUE)
  !inherits(res, "try-error")
}
if(!cmdstan_installed()){
    install_cmdstan()
}
```

```{r}
data <- read.csv("clean-data/master-sub.csv")

head(data)
```

Extract relevant data

```{r}
df <- data[c("ServerWon", "BreakPoint", "Tiebreaker")]

str(df$ServerWon)
str(df$BreakPoint)
str(df$Tiebreaker)

# mean(na.omit(df$ServerWon))
```

Fit model

```{r}

fit <- brm(
    formula = ServerWon ~ BreakPoint + Tiebreaker,
    data = df,
    family = bernoulli(link = "logit"),
    prior = c(
      prior(normal(0,2^2), class = "Intercept"),
      prior(normal(0,1^2), class = "b")
    ),
    chains = 4,
    iter = 2000,
    cores = 4
)

```

Checking results

```{r}

summary(fit)

```

Win probabilities

```{r}

post <- spread_draws(fit, b_Intercept, b_BreakPoint, b_Tiebreaker)

p_alpha <- inv_logit_scaled(post$b_Intercept)
p_bp <- inv_logit_scaled(post$b_Intercept+post$b_BreakPoint)
p_tb <- inv_logit_scaled(post$b_Intercept+post$b_Tiebreaker)

mean(p_alpha)
mean(p_bp)
mean(p_tb)



library(tidybayes)
library(dplyr)
library(ggplot2)

post <- spread_draws(fit, b_Intercept, b_BreakPoint, b_Tiebreaker) %>%
  mutate(
    p_regular  = plogis(b_Intercept),
    p_break    = plogis(b_Intercept + b_BreakPoint),
    p_tiebreak = plogis(b_Intercept + b_Tiebreaker)
  ) %>%
  select(.draw, p_regular, p_break, p_tiebreak) %>%
  pivot_longer(-.draw, names_to = "situation", values_to = "p")

ggplot(post, aes(x = p, y = situation)) +
  stat_pointinterval(.width = c(.5, .8, .95)) +
  xlim(0, 1) +
  labs(x = "P(server wins point)", y = NULL)
```


MCMC Plots

```{r}
library(brms)

# trace plots
mcmc_plot(fit,
          pars = c("b_Intercept", "b_BreakPoint", "b_Tiebreaker"),
          type = "trace")

# overlaid posterior densities by chain
mcmc_plot(fit,
          pars = c("b_Intercept", "b_BreakPoint", "b_Tiebreaker"),
          type = "dens_overlay")

```

Posterior predictive plots

```{r}
newdata <- data.frame(
  Tiebreaker = 0,
  BreakPoint = 1
)

ppd_break <- posterior_epred(
  fit,
  newdata = newdata
  )

ppd_reg <- posterior_epred(
  fit,
  newdata = df[sample(nrow(df), 1),]
)

ppd_tie <- posterior_epred(
  fit,
  newdata = data.frame(
    Tiebreaker = 1,
    BreakPoint = 0
  )
)

preds <- data.frame(
  p_reg = as.vector(ppd_reg),
  p_break = as.vector(ppd_break),
  p_tie = as.vector(ppd_tie)
)
```

```{r}
p <- ggplot(preds) + 
  geom_density(
    aes(p_reg, colour = 'Any point')
  ) + geom_density(
    aes(p_break, colour = 'Breakpoint')
  ) + geom_density(
    aes(p_tie, colour = 'Tiebreak')
  ) +
  xlab('Win probability') +
  ylab('Density')
p
```

```{r}
# compare observed vs predicted proportion of 1's
pp_check(fit, type = "bars")          # barplot of y vs yrep

# check mean statistic
pp_check(fit, type = "stat", stat = "mean")

# if you want distribution of y (0/1) counts
pp_check(fit, type = "hist")

```

```{r}
pp_check(fit, type = "stat", stat = "mean")
```

```{r}
pp_check(fit, type = "bars")
```

```{r}
drel <- df[sample(nrow(df), 10000),]

pp_y <- posterior_epred(
  fit,
  newdata = drel,
)
pp_y <- colMeans(pp_y)
```

```{r}
plot(reliabilitydiag(p = pp_y, y = drel$ServerWon)) +
  xlim(0.55, 0.65) +
  ylim(0, 0.7)
```

